name: Multi-Threaded MapReduce Tests

on:
  push:
    paths:
      - "Multi-threaded MapReduce framework/**"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++

      - name: Compile and run test1
        run: |
          g++ "Multi-threaded MapReduce framework/test1-1_thread_1_process.cpp" -o test1_output
          ./test1_output

      - name: Compile and run test4
        run: |
          g++ "Multi-threaded MapReduce framework/test4-1_thread_4_process.cpp" -o test4_output
          ./test4_output

