name: Multi-Threaded MapReduce Tests

on:
  push:
    paths:
      - "Multi-threaded MapReduce framework/**"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++

      - name: Compile and run test1
        run: |
          g++ "Multi-threaded MapReduce framework/test1-1_thread_1_process.cpp" \
              "Multi-threaded MapReduce framework/MapReduceFramework.cpp" \
              "Multi-threaded MapReduce framework/Barrier.cpp" \
              -o test1_output
          ./test1_executable > test1_output.txt
        
       
      - name: Compare output
        run: diff test1_output.txt "Multi-threaded MapReduce framework/test1-1_thread_1_expected.txt"
